[oc_branch]
OC_SRV ansible_host=34.67.80.108 ansible_port=5987 dns_ip="10.3.80.50"

[et_branch]
ET_SRV ansible_host=34.67.80.108 ansible_port=5988 dns_ip="10.4.80.50"

[all_branches:children]
oc_branch
et_branch

[all_branches:vars]
ansible_user=Administrator@NGH.com
ansible_password=admin
ansible_connection=winrm
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic