[hq_branch]
HQ_SRV ansible_host=35.209.100.72 ansible_port=5985 dns_ip="10.1.160.11"

[cc_branch]
CC_SRV ansible_host=35.209.100.72 ansible_port=5985 dns_ip="10.2.80.11"

[oc_branch]
OC_SRV ansible_host=35.209.100.72 ansible_port=5987 dns_ip="10.3.80.50" ansible_user=Administrator ansible_password=admin

[et_branch]
ET_SRV ansible_host=35.209.100.72 ansible_port=5988 dns_ip="10.4.80.50"

[all_branches:children]
hq_branch
cc_branch
oc_branch
et_branch

[all_branches:vars]
ansible_user=Administrator@NGH.com
ansible_password=admin
ansible_connection=winrm
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
